### ISSUE TITLE
error message when i install

### ISSUE THREAD

**Issue by alidz1982** [bigblog/shorten.io#1]
The script couldn't finish the installation because of the following reason: 

You need to fill in all the fields.

Please, try again.

**Comment by alidz1982** [comment]
![install shorten io_20180110135454](https://user-images.githubusercontent.com/7863061/34774432-97211c14-f60f-11e7-9539-21fd48c4bde0.png)
![install shorten io_20180110140621](https://user-images.githubusercontent.com/7863061/34774433-9756b856-f60f-11e7-9f2e-36538e0886b7.png)

**Comment by jozsefsallai** [comment]
Hey! 
Make sure you create a separate MySQL user and database for the script before starting the installation. I don't recommend using the `root` user for this, especially not without a password. A password is necessary for the script to properly connect to the database. If you have any more issues, please let me know!
